services:
  api-todo-mysql:
    image: bitnami/mysql:latest
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=docker
      - MYSQL_DATABASE=api-todo
      - MYSQL_USER=docker
      - MYSQL_PASSWORD=docker
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
